-- ============================================================
-- 009_patient_links.sql
-- ============================================================
-- PURPOSE
--   Magic link tokens for patient authentication.
--   Patients have NO Supabase auth accounts. They access
--   the My Tiki patient portal via a one-time tokenized URL
--   generated by staff or automatically by the system.
--
-- SECURITY MODEL
--   • The raw 43-char token is NEVER stored in the database.
--   • Only sha256(token) is stored as token_hash TEXT.
--   • The Express middleware requirePatientToken():
--       1. Extracts the raw token from the URL query param
--       2. Computes sha256(token) in Node.js
--       3. Queries patient_links WHERE token_hash = computed_hash
--       4. Checks expires_at and used_at
--   • Multi-use links: used_at remains NULL; access_count
--     increments on each use.
--   • Single-use links: used_at is set on first use; subsequent
--     requests are rejected with 401.
--
-- TOKEN GENERATION (server.js)
--   const { randomBytes, createHash } = require('crypto');
--   const token = randomBytes(32).toString('base64url'); // 43 chars
--   const tokenHash = createHash('sha256').update(token).digest('hex');
--
-- ROLLBACK
--   DROP TABLE IF EXISTS patient_links CASCADE;
-- ============================================================

CREATE TABLE IF NOT EXISTS patient_links (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  clinic_id      UUID        NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  patient_id     UUID        NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  visit_id       UUID        REFERENCES visits(id) ON DELETE SET NULL,

  -- SHA-256 hex of the raw token (raw token never stored)
  token_hash     TEXT        NOT NULL UNIQUE,

  -- Link purpose — determines which patient portal view is shown
  link_type      TEXT        NOT NULL DEFAULT 'portal'
    CHECK (link_type IN (
      'portal',     -- general My Tiki portal access
      'intake',     -- direct link to intake form
      'consent',    -- direct link to consent form
      'followup',   -- direct link to followup form
      'aftercare'   -- aftercare instructions view
    )),

  -- Expiry
  expires_at     TIMESTAMPTZ NOT NULL
    DEFAULT (now() + INTERVAL '72 hours'),

  -- Usage tracking
  -- used_at NULL = multi-use or not yet used
  -- used_at SET  = single-use and already consumed
  used_at        TIMESTAMPTZ,
  access_count   INT         NOT NULL DEFAULT 0,

  -- Who generated this link (clinic_users.user_id or 'system')
  generated_by   TEXT,

  -- Status (active → revoked or expired)
  -- Derived from expires_at + used_at, but denormalized for fast queries
  status         TEXT        NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'revoked', 'expired')),

  revoked_by     TEXT,       -- clinic_users.user_id who revoked
  revoked_at     TIMESTAMPTZ,

  -- Per-link language preference for patient-facing content
  patient_lang   TEXT        DEFAULT 'ko',

  -- Channel the link was sent via (for analytics)
  sent_via       TEXT        CHECK (sent_via IN ('kakao', 'whatsapp', 'sms', 'email', NULL)),

  -- Optional custom message delivered with the link
  custom_message TEXT,

  -- Access timestamps
  first_opened_at    TIMESTAMPTZ,
  last_accessed_at   TIMESTAMPTZ,

  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()

  -- No updated_at: status/access fields are tracked separately above.
);

-- ─────────────────────────────────────────────────────────────
-- Indexes
-- ─────────────────────────────────────────────────────────────

-- Primary auth lookup: token_hash lookup on every patient request
CREATE UNIQUE INDEX IF NOT EXISTS idx_patient_links_token_hash
  ON patient_links(token_hash);

-- Patient's active links (coordinator: view all links for a patient)
CREATE INDEX IF NOT EXISTS idx_patient_links_patient
  ON patient_links(patient_id, expires_at DESC);

-- Visit links (find the active intake/consent link for a visit)
CREATE INDEX IF NOT EXISTS idx_patient_links_visit
  ON patient_links(visit_id, link_type)
  WHERE visit_id IS NOT NULL;

-- Cleanup job: find expired links
CREATE INDEX IF NOT EXISTS idx_patient_links_expires
  ON patient_links(expires_at)
  WHERE used_at IS NULL;

-- ─────────────────────────────────────────────────────────────
-- RLS — defined centrally in 015_rls.sql
-- ─────────────────────────────────────────────────────────────
ALTER TABLE patient_links ENABLE ROW LEVEL SECURITY;
